### ISSUE TITLE
good work

### ISSUE THREAD

**Issue by boneskull** [DylanPiercey/mocha-snap#2]
Hi, just wanted to say that I'm happy this package exists and glad that someone found use for root hooks.  😄

I was trying to use it in [appium](/appium/appium), but ended up dropping it because we still need to support Node.js v12.  When we drop support for that ourselves, I'll be taking another look at this project.

If I had any feature requests...

- allow precise control over the output directory (since it's derived from suite names).  I didn't see how this was possible from the `README`, anyhow.  I tend to use _very long_ suite names, so this can become bothersome.
- allow configuration. If you needed it, you wouldn't `--require mocha-snap`; instead you'd use (e.g.,) `--require setup.js` where `setup.js` could `require('mocha-snap')` and initialize it with some default settings, then re-export the hook(s).  Also interested in how Mocha could make this easier from an end-user or plugin dev perspective.

thanks!

**Comment by DylanPiercey** [comment]
Thanks for checking it out @boneskull!
Since building this module and bringing file system & inline snapshots to mocha I've left jest and not looked back 😛.

The top level API is a bit confusing and probably could use better documentation. Open to feedback of course!

You can override the generated file name via the second argument. If you pass a file extension, eg `.md` it becomes prefixed with a test name generated id. However if you pass a base file name, it will use that as the file name and instead make the output be in a folder based on the generated test name.

You can also override the `__snapshots__` folder via the third argument (https://github.com/DylanPiercey/mocha-snap#custom-__snapshots__-folder).

However as it stands the id generated from the test name will always be there somewhere in part to act as a way to cleanup snapshots from tests that no longer exist. If you have thoughts on how to improve this please share 😄.

For your second point: In general I'd like to avoid config and so far it has not been necessary although your recommendation there makes sense and I'll keep it in mind!
